### ISSUE TITLE
Fails to start.

### ISSUE THREAD

**Issue by bweston92** [panubo/docker-mariadb-galera#1]
Can you explain how this should work as the entrypoint is looking to see if `$1` is "mysql" and fails to create the configuration file.
```
docker run -d --net host --name galera \
  -e WSREP_NODE_ADDRESS=$WSREP_NODE_ADDRESS \
  -e WSREP_CLUSTER_ADDRESS=$WSREP_CLUSTER_ADDRESS \
  -e MYSQL_ROOT_PASSWORD={{ mysql_root_password }} \
  -p 3306:3306 \
  -p 4567:4567/udp \
  -p 4567-4568:4567-4568 \
  -p 4444:4444 \
  -v /mnt/data/galera.service/mysql:/var/lib/mysql:Z \
  panubo/mariadb-galera \
    --wsrep-new-cluster
```

The following works but please advise.
```
docker run -d --net host --name galera \
  -e WSREP_NODE_ADDRESS=$WSREP_NODE_ADDRESS \
  -e WSREP_CLUSTER_ADDRESS=$WSREP_CLUSTER_ADDRESS \
  -e MYSQL_ROOT_PASSWORD={{ mysql_root_password }} \
  -p 3306:3306 \
  -p 4567:4567/udp \
  -p 4567-4568:4567-4568 \
  -p 4444:4444 \
  -v /mnt/data/galera.service/mysql:/var/lib/mysql:Z \
  panubo/mariadb-galera \
    mysqld --wsrep-new-cluster
```

https://github.com/panubo/docker-mariadb-galera/commit/4d599c780a4a1a09ee64e7593da6750537611e6d#diff-7b0b8ef9d1b37843487cf6f08320f5bfR9

**Comment by macropin** [comment]
Good pickup. Let me get back to you. I've just noticed that we're running 
    `mysqld` on the exec line for both the new cluster setup and systemd unit.

**Comment by macropin** [comment]
Let me know if this latest commit resolves your issue.

**Comment by aaron-legalweb** [comment]
When starting a node without the initialization flag "--wsrep-new-cluster" the following error occurs.

command was: "mysqld mysqld --verbose --help --log-bin-index=/tmp/tmp.4fpslDx0kd"

**Comment by macropin** [comment]
I've removed the default `mysqld` argument. Sometimes being clever is not a good idea.
